In [1]:
import torch
import torch.nn as nn # nn is neural network

In [2]:
torch.ones(2,2,2)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [3]:
x = [1,2,3]
torch.tensor(x)

tensor([1, 2, 3])

In [4]:
class Test(nn.Module): #3 layer input , 4 layer hidden , 1 layer output
    
    def __init__(self): #init function like all the layers
        self.hidden = nn.Linear(3,4) #3 input and 4 output units
        self.output = nn.Linear(4,1) #4 input and 1 output unit
   
    def forward(self,x): #forward function do multiplication and return result
        hidden_output = self.hidden(x) #Forward function on input x done by hidden layer
        return self.output(hidden_output) #Forward function on hidden_output done by output layer this is final result

In [5]:
torch.empty((3,3,3))

tensor([[[5.3048e-29, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])

In [6]:
torch.rand(3,3) #0-1 range

tensor([[0.1099, 0.8288, 0.2769],
        [0.1203, 0.2348, 0.5508],
        [0.4485, 0.5143, 0.2044]])

In [7]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
x = torch.ones(3,3)

In [9]:
x.size()

torch.Size([3, 3])

In [10]:
x.shape

torch.Size([3, 3])

In [11]:
x.dtype

torch.float32

In [12]:
y = torch.zeros(3,3,dtype = torch.float32)

In [13]:
y.dtype

torch.float32

In [14]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
y

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
x+y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
torch.cuda.is_available()

True

In [18]:
torch.__version__

'2.7.0+cu126'

In [20]:
z = torch.randn(4,4)
z

tensor([[ 0.4514, -0.3152, -0.2646,  0.5864],
        [-0.8075,  0.5088, -1.4305, -0.8062],
        [-0.1650, -0.1658,  0.1431, -1.5285],
        [-2.2398, -0.5996, -0.6173, -0.2764]])

In [29]:
z.view(-1,1).size()

torch.Size([16, 1])

In [30]:
torch.device("cuda" if torch.cuda.is_available() else "cpu")

device(type='cuda')

In [43]:
x = torch.randn(3,requires_grad = True)

y = x + 2

print(x)
print(y)
print(y.grad_fn)

tensor([ 0.2021, -1.1593,  0.1231], requires_grad=True)
tensor([2.2021, 0.8407, 2.1231], grad_fn=<AddBackward0>)


In [44]:
y.sum()

tensor(5.1659, grad_fn=<SumBackward0>)

In [45]:
print(x.grad)

y.sum().backward() #dy/dx works only on scalar values

x.grad


None


tensor([1., 1., 1.])

In [47]:
a = torch.randn(2,2)
a

tensor([[ 0.2828,  0.6096],
        [-0.5519, -0.4078]])

In [48]:
a.requires_grad

False

In [49]:
a.requires_grad_(True)

tensor([[ 0.2828,  0.6096],
        [-0.5519, -0.4078]], requires_grad=True)

In [50]:
a.requires_grad

True

In [54]:
a = torch.tensor([1,2,3], dtype = torch.float32)
a.mean()

tensor(2.)