In [68]:
import torch

f(x) = wx + b

In [ ]:
x = torch.tensor([1,2,3,4,5,6,7,8],dtype = torch.float32)
y = torch.tensor([3,5,7,9,11,13,15,17],dtype = torch.float32) #y = 2x + 1
w = torch.tensor(0.0,dtype = torch.float32,requires_grad = True)
b = torch.tensor(0.0,dtype = torch.float32, requires_grad = True)

In [70]:
def forward(x):
    return w * x + b

In [71]:
def loss(y,y_pred):
    return ((y_pred - y) ** 2).mean()

In [72]:
X_test = 5.0 
forward(X_test).item() #forward basically returns prediction , item converts from tensor to python float

0.0

In [74]:
learning_rate = 0.01
epochs = 10000

for i in range(epochs):
    y_pred = forward(x)

    l = loss(y,y_pred) #calculates loss

    l.backward() # does dl/dw  and dl/db and is stored in w.grad and b.grad

    with torch.no_grad(): #doesnt use this for computing gradients
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    w.grad.zero_() #zero the gradients
    b.grad.zero_()

    if (i + 1) % 1000 == 0:
        print(f"Epoch {i+1}: w = {w.item()}, b = {b.item()} loss = {l.item()}")

print(f"Prediction after training {X_test} = {forward(X_test).item()}") #final output
print(f"Weight is {w}, bias is {b}")

Epoch 1000: w = 2.000002145767212, b = 0.9999890327453613 loss = 2.4421353828074643e-11
Epoch 2000: w = 2.000002145767212, b = 0.9999890327453613 loss = 2.4421353828074643e-11
Epoch 3000: w = 2.000002145767212, b = 0.9999890327453613 loss = 2.4421353828074643e-11
Epoch 4000: w = 2.000002145767212, b = 0.9999890327453613 loss = 2.4421353828074643e-11
Epoch 5000: w = 2.000002145767212, b = 0.9999890327453613 loss = 2.4421353828074643e-11
Epoch 6000: w = 2.000002145767212, b = 0.9999890327453613 loss = 2.4421353828074643e-11
Epoch 7000: w = 2.000002145767212, b = 0.9999890327453613 loss = 2.4421353828074643e-11
Epoch 8000: w = 2.000002145767212, b = 0.9999890327453613 loss = 2.4421353828074643e-11
Epoch 9000: w = 2.000002145767212, b = 0.9999890327453613 loss = 2.4421353828074643e-11
Epoch 10000: w = 2.000002145767212, b = 0.9999890327453613 loss = 2.4421353828074643e-11
Prediction after training 5.0 = 11.0
Weight is 2.000002145767212, bias is 0.9999890327453613


In [107]:
import torch
import torch.nn as nn
import torch.optim 

In [108]:
x = torch.tensor( [ [1],[2],[3],[4],[5],[6],[7],[8] ], dtype = torch.float32) #nn expects 2d tensors
y = torch.tensor( [ [3],[5],[7],[9],[11],[13],[15],[17] ], dtype = torch.float32)

x.shape

torch.Size([8, 1])

In [109]:
x.shape[0] #no of samples
x.shape[1] #input features

1

In [115]:
x_test = torch.tensor( [ [5] ],dtype = torch.float32)

In [ ]:
class LinearRegression(nn.Module):
    def __init__(self,input_dim,output_dim):
        super().__init__() #tracks paramenters and stuff and basically setting up 
        self.lin = nn.Linear(input_dim,output_dim) #creates the weight and bias

    def forward(self,x):
        return self.lin(x) #performs wx + b

model = LinearRegression(x.shape[1],x.shape[1]) #Expects the i/p no of features and o/p no of features

print(f"Before training prediction {x_test.item()} = {model(x_test).item()}")

Before training prediction 5.0 = 3.670987129211426


In [117]:
list(model.parameters())

[Parameter containing:
 tensor([[0.7669]], requires_grad=True),
 Parameter containing:
 tensor([-0.1636], requires_grad=True)]

In [118]:
learning_rate = 0.01
epoch = 10000


loss = nn.MSELoss() #mean square error loss
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate) #Stochastic gradient descent
#model parameters include the weights and biases

for i in range(epoch):
    y_pred = model(x) #internally calls the forward fucnction

    l = loss(y,y_pred) #calls the mse loss thingy to calculate loss

    l.backward() #calculate gradient

    optimizer.step() #changes weights and biases

    optimizer.zero_grad()

    if (i + 1) % 1000 == 0:
        w,b = model.parameters() #parameters unpacking
        print(f"Epoch: {i+1}: w = {w.item()} , b = {b.item()}, loss = {l.item()} ")

print(f"Prediction after training {x_test.item()}, = {model(x_test).item()}")


Epoch: 1000: w = 2.002980947494507 , b = 0.9832407832145691, loss = 5.830454392707907e-05 
Epoch: 2000: w = 2.0000545978546143 , b = 0.999692440032959, loss = 1.9630910230716836e-08 
Epoch: 3000: w = 2.000002145767212 , b = 0.9999890327453613, loss = 2.4421353828074643e-11 
Epoch: 4000: w = 2.000002145767212 , b = 0.9999890327453613, loss = 2.4421353828074643e-11 
Epoch: 5000: w = 2.000002145767212 , b = 0.9999890327453613, loss = 2.4421353828074643e-11 
Epoch: 6000: w = 2.000002145767212 , b = 0.9999890327453613, loss = 2.4421353828074643e-11 
Epoch: 7000: w = 2.000002145767212 , b = 0.9999890327453613, loss = 2.4421353828074643e-11 
Epoch: 8000: w = 2.000002145767212 , b = 0.9999890327453613, loss = 2.4421353828074643e-11 
Epoch: 9000: w = 2.000002145767212 , b = 0.9999890327453613, loss = 2.4421353828074643e-11 
Epoch: 10000: w = 2.000002145767212 , b = 0.9999890327453613, loss = 2.4421353828074643e-11 
Prediction after training 5.0, = 11.0


In [119]:
list(model.parameters()) #2x + 1 perfect

[Parameter containing:
 tensor([[2.0000]], requires_grad=True),
 Parameter containing:
 tensor([1.0000], requires_grad=True)]